import type { SpellCombatType, SpellDefinition, VocationName } from '../../content-schema/src';
import type { CharacterState, GameContent } from './types';

export type HotbarActionKind = 'spell' | 'rune' | 'potion';

export interface HotbarRuneDefinition {
  id: number;
  name: string;
  words: string;
  kind: 'rune';
  category: 'attack' | 'healing' | 'support';
  requiredLevel: number;
  requiredMagicLevel: number;
  vocations: VocationName[];
  range: number;
  area: 'target' | 'square-1x1';
  combatType: SpellCombatType;
  cooldownMs: number;
  effectId: number;
  projectileId: number;
  description: string;
}

export interface HotbarPotionDefinition {
  id: number;
  name: string;
  kind: 'potion';
  category: 'healing' | 'mana' | 'support';
  requiredLevel: number;
  vocations: VocationName[];
  cooldownMs: number;
  effectId: number;
  healMin?: number;
  healMax?: number;
  manaMin?: number;
  manaMax?: number;
  description: string;
}

export type HotbarActionItem =
  | { kind: 'spell'; spell: SpellDefinition }
  | { kind: 'rune'; rune: HotbarRuneDefinition }
  | { kind: 'potion'; potion: HotbarPotionDefinition };

const ALL_VOCATIONS: VocationName[] = [
  'Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid',
  'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'
];

export const HOTBAR_RUNES: HotbarRuneDefinition[] = [
  {
    id: 2268,
    name: 'Sudden Death',
    words: 'adori gran mort',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 45,
    requiredMagicLevel: 15,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'target',
    combatType: 'physical',
    cooldownMs: 2000,
    effectId: 16,
    projectileId: 5,
    description: 'Dispara uma descarga massiva de energia da morte em alvo único.',
  },
  {
    id: 2311,
    name: 'Heavy Magic Missile',
    words: 'adori vis',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 25,
    requiredMagicLevel: 3,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin'],
    range: 4,
    area: 'target',
    combatType: 'energy',
    cooldownMs: 2000,
    effectId: 38,
    projectileId: 5,
    description: 'Dispara um projétil concentrado de energia arcana no alvo.',
  },
  {
    id: 2304,
    name: 'Great Fireball',
    words: 'adori mas flam',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 30,
    requiredMagicLevel: 4,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'square-1x1',
    combatType: 'fire',
    cooldownMs: 2000,
    effectId: 37,
    projectileId: 4,
    description: 'Bola de fogo explosiva que queima todos os monstros em área.',
  },
  {
    id: 2274,
    name: 'Avalanche',
    words: 'adori mas frigo',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 30,
    requiredMagicLevel: 4,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'square-1x1',
    combatType: 'ice',
    cooldownMs: 2000,
    effectId: 42,
    projectileId: 37,
    description: 'Tempestade glacial congelante que causa dano de gelo em área.',
  },
  {
    id: 2313,
    name: 'Explosion',
    words: 'adori mas mort',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 31,
    requiredMagicLevel: 6,
    vocations: [
      'Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid',
      'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'
    ],
    range: 4,
    area: 'square-1x1',
    combatType: 'physical',
    cooldownMs: 2000,
    effectId: 10,
    projectileId: 5,
    description: 'Detonação de impacto cinético que estilhaça inimigos em área.',
  },
  {
    id: 2273,
    name: 'Ultimate Healing Rune',
    words: 'adura vita',
    kind: 'rune',
    category: 'healing',
    requiredLevel: 24,
    requiredMagicLevel: 4,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'],
    range: 4,
    area: 'target',
    combatType: 'healing',
    cooldownMs: 2000,
    effectId: 13,
    projectileId: 0,
    description: 'Runa de cura — lançada em você ou em um aliado por perto.',
  },
  {
    id: 2302,
    name: 'Fireball Rune',
    words: 'adori flam',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 27,
    requiredMagicLevel: 4,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin'],
    range: 4,
    area: 'target',
    combatType: 'fire',
    cooldownMs: 2000,
    effectId: 37,
    projectileId: 4,
    description: 'Bola de fogo de alvo único.',
  },
  {
    id: 2271,
    name: 'Icicle Rune',
    words: 'adori frigo',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 28,
    requiredMagicLevel: 4,
    vocations: ['Druid', 'Elder Druid', 'Sorcerer', 'Master Sorcerer'],
    range: 4,
    area: 'target',
    combatType: 'ice',
    cooldownMs: 2000,
    effectId: 42,
    projectileId: 37,
    description: 'Projétil gélido de gelo.',
  },
  {
    id: 2288,
    name: 'Stone Shower Rune',
    words: 'adori mas tera',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 28,
    requiredMagicLevel: 4,
    vocations: ['Druid', 'Elder Druid', 'Sorcerer', 'Master Sorcerer'],
    range: 4,
    area: 'square-1x1',
    combatType: 'earth',
    cooldownMs: 2000,
    effectId: 14,
    projectileId: 5,
    description: 'Chuva de pedras e terra em área.',
  },
  {
    id: 2315,
    name: 'Thunderstorm Rune',
    words: 'adori mas vis',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 28,
    requiredMagicLevel: 4,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'square-1x1',
    combatType: 'energy',
    cooldownMs: 2000,
    effectId: 11,
    projectileId: 5,
    description: 'Tempestade elétrica em área.',
  },
  {
    id: 2287,
    name: 'Light Magic Missile Rune',
    words: 'adori min vis',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 15,
    requiredMagicLevel: 0,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'],
    range: 4,
    area: 'target',
    combatType: 'energy',
    cooldownMs: 2000,
    effectId: 38,
    projectileId: 5,
    description: 'Míssil mágico leve de energia.',
  },
  {
    id: 2292,
    name: 'Stalagmite Rune',
    words: 'adori tera',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 24,
    requiredMagicLevel: 3,
    vocations: ['Druid', 'Elder Druid', 'Sorcerer', 'Master Sorcerer'],
    range: 4,
    area: 'target',
    combatType: 'earth',
    cooldownMs: 2000,
    effectId: 14,
    projectileId: 5,
    description: 'Espinho de rocha que perfura o alvo com dano de terra.',
  },
  {
    id: 2295,
    name: 'Holy Missile Rune',
    words: 'adori san',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 27,
    requiredMagicLevel: 4,
    vocations: ['Paladin', 'Royal Paladin'],
    range: 4,
    area: 'target',
    combatType: 'holy',
    cooldownMs: 2000,
    effectId: 49,
    projectileId: 38,
    description: 'Projétil de luz sagrada divino exclusivo de paladinos.',
  },
  {
    id: 2293,
    name: 'Magic Wall Rune',
    words: 'adevo grav tera',
    kind: 'rune',
    category: 'support',
    requiredLevel: 32,
    requiredMagicLevel: 9,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'target',
    combatType: 'support',
    cooldownMs: 2000,
    effectId: 14,
    projectileId: 5,
    description: 'Cria uma muralha de energia intransponível por tempo limitado.',
  },
  {
    id: 2269,
    name: 'Wild Growth Rune',
    words: 'adevo grav vita',
    kind: 'rune',
    category: 'support',
    requiredLevel: 27,
    requiredMagicLevel: 8,
    vocations: ['Druid', 'Elder Druid'],
    range: 4,
    area: 'target',
    combatType: 'support',
    cooldownMs: 2000,
    effectId: 45,
    projectileId: 5,
    description: 'Cria um arbusto vivo que bloqueia a passagem.',
  },
  {
    id: 2278,
    name: 'Paralyze Rune',
    words: 'adana ani',
    kind: 'rune',
    category: 'support',
    requiredLevel: 54,
    requiredMagicLevel: 18,
    vocations: ['Druid', 'Elder Druid'],
    range: 4,
    area: 'target',
    combatType: 'support',
    cooldownMs: 2000,
    effectId: 13,
    projectileId: 0,
    description: 'Reduz severamente a velocidade de movimento do alvo.',
  },
  {
    id: 2261,
    name: 'Destroy Field Rune',
    words: 'adito grav',
    kind: 'rune',
    category: 'support',
    requiredLevel: 17,
    requiredMagicLevel: 3,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'],
    range: 4,
    area: 'target',
    combatType: 'support',
    cooldownMs: 2000,
    effectId: 10,
    projectileId: 0,
    description: 'Remove campos de fogo, veneno ou energia do chão.',
  },
  {
    id: 2310,
    name: 'Desintegrate Rune',
    words: 'adito tera',
    kind: 'rune',
    category: 'support',
    requiredLevel: 21,
    requiredMagicLevel: 4,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'],
    range: 1,
    area: 'target',
    combatType: 'support',
    cooldownMs: 2000,
    effectId: 10,
    projectileId: 0,
    description: 'Desintegra itens ou corpos do chão adjacente.',
  },
  {
    id: 2291,
    name: 'Chameleon Rune',
    words: 'adevo ina',
    kind: 'rune',
    category: 'support',
    requiredLevel: 27,
    requiredMagicLevel: 4,
    vocations: ['Druid', 'Elder Druid', 'Sorcerer', 'Master Sorcerer'],
    range: 1,
    area: 'target',
    combatType: 'support',
    cooldownMs: 2000,
    effectId: 10,
    projectileId: 0,
    description: 'Assume a aparência de um item no chão.',
  },
  {
    id: 2290,
    name: 'Convince Creature Rune',
    words: 'adeta sio',
    kind: 'rune',
    category: 'support',
    requiredLevel: 16,
    requiredMagicLevel: 5,
    vocations: ['Druid', 'Elder Druid', 'Sorcerer', 'Master Sorcerer'],
    range: 1,
    area: 'target',
    combatType: 'support',
    cooldownMs: 2000,
    effectId: 10,
    projectileId: 0,
    description: 'Convença uma criatura a lutar ao seu lado.',
  },
  {
    id: 2266,
    name: 'Cure Poison Rune',
    words: 'adana pox',
    kind: 'rune',
    category: 'healing',
    requiredLevel: 15,
    requiredMagicLevel: 0,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'],
    range: 4,
    area: 'target',
    combatType: 'healing',
    cooldownMs: 2000,
    effectId: 12,
    projectileId: 0,
    description: 'Cura envenenamento em você ou em um aliado.',
  },
  {
    id: 2265,
    name: 'Intense Healing Rune',
    words: 'adura gran',
    kind: 'rune',
    category: 'healing',
    requiredLevel: 15,
    requiredMagicLevel: 1,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin', 'Knight', 'Elite Knight'],
    range: 4,
    area: 'target',
    combatType: 'healing',
    cooldownMs: 2000,
    effectId: 13,
    projectileId: 0,
    description: 'Cura intermediária para você ou um aliado.',
  },
  {
    id: 2316,
    name: 'Animate Dead Rune',
    words: 'adana mort',
    kind: 'rune',
    category: 'support',
    requiredLevel: 27,
    requiredMagicLevel: 4,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 1,
    area: 'target',
    combatType: 'support',
    cooldownMs: 2000,
    effectId: 16,
    projectileId: 0,
    description: 'Ergue esqueletos a partir de corpos de criaturas.',
  },
  {
    id: 2308,
    name: 'Soulfire Rune',
    words: 'adevo res flam',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 27,
    requiredMagicLevel: 7,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'target',
    combatType: 'fire',
    cooldownMs: 2000,
    effectId: 37,
    projectileId: 4,
    description: 'Queima a alma do alvo causando dano contínuo.',
  },
  {
    id: 2301,
    name: 'Fire Field Rune',
    words: 'adevo grav flam',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 15,
    requiredMagicLevel: 1,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'target',
    combatType: 'fire',
    cooldownMs: 2000,
    effectId: 37,
    projectileId: 4,
    description: 'Cria um campo de chamas ardentes.',
  },
  {
    id: 2303,
    name: 'Fire Wall Rune',
    words: 'adevo mas grav flam',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 33,
    requiredMagicLevel: 9,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'target',
    combatType: 'fire',
    cooldownMs: 2000,
    effectId: 37,
    projectileId: 4,
    description: 'Cria uma parede de fogo contínua.',
  },
  {
    id: 2305,
    name: 'Fire Bomb Rune',
    words: 'adevo mas flam',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 27,
    requiredMagicLevel: 5,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'square-1x1',
    combatType: 'fire',
    cooldownMs: 2000,
    effectId: 37,
    projectileId: 4,
    description: 'Explosão de fogo que incendeia 9 quadrantes.',
  },
  {
    id: 2277,
    name: 'Energy Field Rune',
    words: 'adevo grav vis',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 18,
    requiredMagicLevel: 3,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'target',
    combatType: 'energy',
    cooldownMs: 2000,
    effectId: 38,
    projectileId: 5,
    description: 'Cria um campo de energia elétrica.',
  },
  {
    id: 2279,
    name: 'Energy Wall Rune',
    words: 'adevo mas grav vis',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 41,
    requiredMagicLevel: 9,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'target',
    combatType: 'energy',
    cooldownMs: 2000,
    effectId: 38,
    projectileId: 5,
    description: 'Cria uma parede de raios elétricos.',
  },
  {
    id: 2262,
    name: 'Energy Bomb Rune',
    words: 'adevo mas vis',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 37,
    requiredMagicLevel: 10,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'square-1x1',
    combatType: 'energy',
    cooldownMs: 2000,
    effectId: 38,
    projectileId: 5,
    description: 'Bomba de energia elétrica que eletrifica 9 quadrantes.',
  },
  {
    id: 2285,
    name: 'Poison Field Rune',
    words: 'adevo grav pox',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 14,
    requiredMagicLevel: 0,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'target',
    combatType: 'earth',
    cooldownMs: 2000,
    effectId: 12,
    projectileId: 5,
    description: 'Cria um campo de poça de veneno.',
  },
  {
    id: 2289,
    name: 'Poison Wall Rune',
    words: 'adevo mas grav pox',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 29,
    requiredMagicLevel: 5,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'target',
    combatType: 'earth',
    cooldownMs: 2000,
    effectId: 12,
    projectileId: 5,
    description: 'Cria uma barreira de gás venenoso.',
  },
  {
    id: 2286,
    name: 'Poison Bomb Rune',
    words: 'adevo mas pox',
    kind: 'rune',
    category: 'attack',
    requiredLevel: 25,
    requiredMagicLevel: 4,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    range: 4,
    area: 'square-1x1',
    combatType: 'earth',
    cooldownMs: 2000,
    effectId: 12,
    projectileId: 5,
    description: 'Detonação de veneno tóxico em área.',
  },
];

export const HOTBAR_POTIONS: HotbarPotionDefinition[] = [
  {
    id: 8704,
    name: 'Lesser Health Potion',
    kind: 'potion',
    category: 'healing',
    requiredLevel: 1,
    vocations: ALL_VOCATIONS,
    cooldownMs: 1000,
    effectId: 15,
    healMin: 63,
    healMax: 88,
    description: 'Bebe sozinha quando a regra dela passa.',
  },
  {
    id: 7618,
    name: 'Health Potion',
    kind: 'potion',
    category: 'healing',
    requiredLevel: 1,
    vocations: ALL_VOCATIONS,
    cooldownMs: 1000,
    effectId: 15,
    healMin: 150,
    healMax: 200,
    description: 'Poção básica que recupera entre 150 e 200 de vida (HP).',
  },
  {
    id: 7588,
    name: 'Strong Health Potion',
    kind: 'potion',
    category: 'healing',
    requiredLevel: 50,
    vocations: ['Knight', 'Elite Knight', 'Paladin', 'Royal Paladin'],
    cooldownMs: 1000,
    effectId: 15,
    healMin: 300,
    healMax: 400,
    description: 'Poção aprimorada que recupera entre 300 e 400 de vida (HP).',
  },
  {
    id: 7591,
    name: 'Great Health Potion',
    kind: 'potion',
    category: 'healing',
    requiredLevel: 80,
    vocations: ['Knight', 'Elite Knight'],
    cooldownMs: 1000,
    effectId: 15,
    healMin: 500,
    healMax: 700,
    description: 'Poção robusta exclusiva para cavaleiros que recupera 500 a 700 HP.',
  },
  {
    id: 8473,
    name: 'Ultimate Health Potion',
    kind: 'potion',
    category: 'healing',
    requiredLevel: 130,
    vocations: ['Knight', 'Elite Knight'],
    cooldownMs: 1000,
    effectId: 15,
    healMin: 800,
    healMax: 1000,
    description: 'Elixir supremo que recupera 800 a 1000 HP instantaneamente.',
  },
  {
    id: 7620,
    name: 'Mana Potion',
    kind: 'potion',
    category: 'mana',
    requiredLevel: 1,
    vocations: ALL_VOCATIONS,
    cooldownMs: 1000,
    effectId: 13,
    manaMin: 75,
    manaMax: 125,
    description: 'Infusão arcana que restaura entre 75 e 125 de mana (MP).',
  },
  {
    id: 7589,
    name: 'Strong Mana Potion',
    kind: 'potion',
    category: 'mana',
    requiredLevel: 50,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid', 'Paladin', 'Royal Paladin'],
    cooldownMs: 1000,
    effectId: 13,
    manaMin: 115,
    manaMax: 185,
    description: 'Infusão mágica potente que restaura entre 115 e 185 de mana.',
  },
  {
    id: 7590,
    name: 'Great Mana Potion',
    kind: 'potion',
    category: 'mana',
    requiredLevel: 80,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    cooldownMs: 1000,
    effectId: 13,
    manaMin: 150,
    manaMax: 250,
    description: 'Elixir místico de alta graduação que recupera 150 a 250 de mana.',
  },
  {
    id: 8472,
    name: 'Great Spirit Potion',
    kind: 'potion',
    category: 'healing',
    requiredLevel: 80,
    vocations: ['Paladin', 'Royal Paladin'],
    cooldownMs: 1000,
    effectId: 15,
    healMin: 200,
    healMax: 400,
    manaMin: 100,
    manaMax: 200,
    description: 'Tônico espiritual sagrado que recupera vida e mana ao mesmo tempo.',
  },
  {
    id: 26031,
    name: 'Supreme Health Potion',
    kind: 'potion',
    category: 'healing',
    requiredLevel: 200,
    vocations: ['Knight', 'Elite Knight'],
    cooldownMs: 1000,
    effectId: 15,
    healMin: 900,
    healMax: 1200,
    description: 'A poção de cura mais poderosa do Tibia 11, recupera 900 a 1200 HP.',
  },
  {
    id: 26029,
    name: 'Ultimate Mana Potion',
    kind: 'potion',
    category: 'mana',
    requiredLevel: 130,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    cooldownMs: 1000,
    effectId: 13,
    manaMin: 400,
    manaMax: 550,
    description: 'Poção de mana de alta classe introduzida no Tibia 11, recupera 400 a 550 MP.',
  },
  {
    id: 26030,
    name: 'Ultimate Spirit Potion',
    kind: 'potion',
    category: 'healing',
    requiredLevel: 130,
    vocations: ['Paladin', 'Royal Paladin'],
    cooldownMs: 1000,
    effectId: 15,
    healMin: 400,
    healMax: 500,
    manaMin: 350,
    manaMax: 450,
    description: 'Poção mística suprema do Tibia 11 para paladinos, recupera HP e MP simultaneamente.',
  },
  {
    id: 8474,
    name: 'Antidote Potion',
    kind: 'potion',
    category: 'healing',
    requiredLevel: 1,
    vocations: ALL_VOCATIONS,
    cooldownMs: 1000,
    effectId: 15,
    description: 'Cura envenenamento e restaura o organismo.',
  },
  {
    id: 7439,
    name: 'Berserk Potion',
    kind: 'potion',
    category: 'support',
    requiredLevel: 1,
    vocations: ['Knight', 'Elite Knight', 'Paladin', 'Royal Paladin'],
    cooldownMs: 2000,
    effectId: 15,
    description: 'Aumenta habilidades corpo a corpo temporariamente.',
  },
  {
    id: 7440,
    name: 'Mastermind Potion',
    kind: 'potion',
    category: 'support',
    requiredLevel: 1,
    vocations: ['Sorcerer', 'Master Sorcerer', 'Druid', 'Elder Druid'],
    cooldownMs: 2000,
    effectId: 13,
    description: 'Aumenta temporariamente o Magic Level.',
  },
  {
    id: 7443,
    name: 'Bullseye Potion',
    kind: 'potion',
    category: 'support',
    requiredLevel: 1,
    vocations: ['Paladin', 'Royal Paladin'],
    cooldownMs: 2000,
    effectId: 15,
    description: 'Aumenta a precisão de combate à distância.',
  },
];

export function findHotbarAction(id: number, content: GameContent): HotbarActionItem | undefined {
  const potion = HOTBAR_POTIONS.find((p) => p.id === id);
  if (potion) return { kind: 'potion', potion };

  const rune = HOTBAR_RUNES.find((r) => r.id === id);
  if (rune) return { kind: 'rune', rune };

  const spell = content.spells.find((s) => s.spellId === id);
  if (spell) return { kind: 'spell', spell };

  return undefined;
}

export function isHotbarActionUnlocked(character: CharacterState, action: HotbarActionItem): boolean {
  if (action.kind === 'potion') {
    return character.level >= action.potion.requiredLevel && action.potion.vocations.includes(character.vocation);
  }
  if (action.kind === 'rune') {
    return (
      character.level >= action.rune.requiredLevel &&
      character.skills.magicLevel >= action.rune.requiredMagicLevel &&
      action.rune.vocations.includes(character.vocation)
    );
  }
  return character.level >= action.spell.requiredLevel && action.spell.vocations.includes(character.vocation);
}

export function getBestHealthPotionForCharacter(character: CharacterState): HotbarPotionDefinition | undefined {
  const eligible = HOTBAR_POTIONS.filter((potion) => {
    if (potion.category !== 'healing' || typeof potion.healMin !== 'number') return false;
    return isHotbarActionUnlocked(character, { kind: 'potion', potion });
  });

  if (eligible.length === 0) {
    return HOTBAR_POTIONS.find((p) => p.id === 7618) ?? HOTBAR_POTIONS[0];
  }
  eligible.sort((a, b) => b.requiredLevel - a.requiredLevel || (b.healMax ?? 0) - (a.healMax ?? 0));
  return eligible[0];
}

export function ensureHealthPotionInHotbar(character: CharacterState, content: GameContent): number | undefined {
  if (!character.hotbar) character.hotbar = [];

  const existingPotionId = character.hotbar.find((id) => {
    if (typeof id !== 'number' || id === 0) return false;
    const action = findHotbarAction(id, content);
    return action?.kind === 'potion' && action.potion.category === 'healing';
  });

  if (existingPotionId) return existingPotionId;

  const bestPotion = getBestHealthPotionForCharacter(character);
  if (!bestPotion) return undefined;

  const emptyIndex = character.hotbar.findIndex((id) => typeof id !== 'number' || id === 0);
  if (emptyIndex !== -1) {
    character.hotbar[emptyIndex] = bestPotion.id;
  } else if (character.hotbar.length < 20) {
    character.hotbar.push(bestPotion.id);
  } else {
    character.hotbar[0] = bestPotion.id;
  }

  return bestPotion.id;
}

