// apps/web/lib/cyclopediaData.ts
// Data motor for Tibia 11 Authentic Cyclopedia (Items, Bestiary, Bosstiary, Boss Points, Character)
import rawCyclopediaCatalog from '@/content/generated/cyclopedia-catalog.json';

export interface ItemEntry {
  id: number;
  name: string;
  category: string;
  attack: number;
  defense: number;
  twoHanded: boolean;
  level: number;
  vocations: string[];
  imbuements: string;
  categoriesText: string;
  price: number;
  droppedBy: string[];
  spriteUrl: string;
}

export type CyclopediaItem = ItemEntry;

export interface ElementalResistances {
  physical: number; // -100 to 100 (% of damage modification/resistance)
  energy: number;
  earth: number;
  fire: number;
  ice: number;
  holy: number;
  death: number;
}

export interface BestiaryMonster {
  id: string;
  name: string;
  stars: number; // 1 to 4
  difficulty: 'Fácil' | 'Médio' | 'Difícil' | 'Extremo';
  killsNeeded: number; // e.g. 250, 500, 1000
  hp: number;
  exp: number;
  speed: number;
  armor: number;
  spriteUrl: string;
  resistances: ElementalResistances;
  drops: Array<{
    id: number;
    name: string;
    rare: boolean;
    count?: number;
  }>;
  locations: string[];
}

export interface BosstiaryBoss {
  id: string;
  name: string;
  tier: 'Archfoe' | 'Bane' | 'Nemesis';
  stars: number; // 1 to 3
  prowess: number;
  expertise: number;
  mastery: number;
  hp: number;
  exp: number;
  summons: string[];
  cooldown: string;
  spriteUrl: string;
  resistances: ElementalResistances;
  dropsCommon: Array<{ id: number; name: string }>;
  dropsRare: Array<{ id: number; name: string }>;
}

export const ITEM_CATEGORIES = [
  'Armas (corpo a corpo)',
  'Armas (distância)',
  'Wands & Rods',
  'Escudos',
  'Elmos',
  'Armaduras',
  'Calças',
  'Botas',
  'Amuletos',
  'Anéis',
  'Trinkets',
] as const;

export type ItemCategory = (typeof ITEM_CATEGORIES)[number];

// Canonical items list matching reference Screenshots 1 and authentic Tibia item catalog
const INITIAL_CANONICAL_ITEMS: ItemEntry[] = [
  {
    id: 7414,
    name: 'Abyss hammer',
    category: 'Armas (corpo a corpo)',
    attack: 47,
    defense: 21,
    twoHanded: true,
    level: 60,
    vocations: ['Knight'],
    imbuements: '3 slot(s) de imbuement',
    categoriesText: 'crítico, dano elemental, life leech, mana leech, skill club',
    price: 20000,
    droppedBy: [
      'The Nightmare Beast',
      'Alptramun',
      'Ferumbras Mortal Shell',
      'Grimeleech',
      'Quara Raider',
    ],
    spriteUrl: '/generated/cyclopedia/items/item-7414.png',
  },
  {
    id: 7436,
    name: 'Angelic axe',
    category: 'Armas (corpo a corpo)',
    attack: 44,
    defense: 21,
    twoHanded: false,
    level: 50,
    vocations: ['Knight'],
    imbuements: '2 slot(s) de imbuement',
    categoriesText: 'crítico, dano elemental, life leech, mana leech, skill axe',
    price: 5000,
    droppedBy: ['Falcon Knight', 'Grand Master Oberon', 'Hero', 'Valkyrie'],
    spriteUrl: '/generated/cyclopedia/items/item-7436.png',
  },
  {
    id: 2453,
    name: 'Arcane staff',
    category: 'Armas (corpo a corpo)',
    attack: 50,
    defense: 30,
    twoHanded: true,
    level: 75,
    vocations: ['Sorcerer', 'Druid'],
    imbuements: '2 slot(s) de imbuement',
    categoriesText: 'crítico, mana leech, magic level',
    price: 50000,
    droppedBy: ['Warlock', 'Grand Master Oberon', 'Demon', 'Ferumbras'],
    spriteUrl: '/generated/cyclopedia/items/item-2453.png',
  },
  {
    id: 7404,
    name: 'Assassin dagger',
    category: 'Armas (corpo a corpo)',
    attack: 40,
    defense: 12,
    twoHanded: false,
    level: 40,
    vocations: ['Knight', 'Paladin'],
    imbuements: '2 slot(s) de imbuement',
    categoriesText: 'crítico, dano elemental, life leech, skill sword',
    price: 20000,
    droppedBy: ['Assassin', 'Bandit', 'Dark Torturer', 'Hero'],
    spriteUrl: '/generated/cyclopedia/items/item-7404.png',
  },
  {
    id: 2400,
    name: 'Magic sword',
    category: 'Armas (corpo a corpo)',
    attack: 48,
    defense: 35,
    twoHanded: false,
    level: 80,
    vocations: ['Knight'],
    imbuements: '3 slot(s) de imbuement',
    categoriesText: 'crítico, dano elemental, life leech, mana leech, skill sword',
    price: 90000,
    droppedBy: ['Demon', 'Annihilator', 'Ferumbras', 'Orshabaal'],
    spriteUrl: '/generated/cyclopedia/items/item-2400.png',
  },
  {
    id: 2431,
    name: 'Stonecutter axe',
    category: 'Armas (corpo a corpo)',
    attack: 50,
    defense: 30,
    twoHanded: false,
    level: 90,
    vocations: ['Knight'],
    imbuements: '3 slot(s) de imbuement',
    categoriesText: 'crítico, dano elemental, life leech, mana leech, skill axe',
    price: 90000,
    droppedBy: ['Demon', 'Juggernaut', 'Morgaroth', 'Ghazbaran'],
    spriteUrl: '/generated/cyclopedia/items/item-2431.png',
  },
  {
    id: 2421,
    name: 'Thunder hammer',
    category: 'Armas (corpo a corpo)',
    attack: 49,
    defense: 35,
    twoHanded: false,
    level: 85,
    vocations: ['Knight'],
    imbuements: '3 slot(s) de imbuement',
    categoriesText: 'crítico, dano elemental, life leech, mana leech, skill club',
    price: 90000,
    droppedBy: ['Morgaroth', 'Orshabaal', 'Ghazbaran'],
    spriteUrl: '/generated/cyclopedia/items/item-2421.png',
  },
  {
    id: 2456,
    name: 'Bow',
    category: 'Armas (distância)',
    attack: 0,
    defense: 0,
    twoHanded: true,
    level: 0,
    vocations: ['Paladin'],
    imbuements: '1 slot(s) de imbuement',
    categoriesText: 'distância, precisão',
    price: 130,
    droppedBy: ['Elf Scout', 'Minotaur Archer', 'Hunter'],
    spriteUrl: '/generated/cyclopedia/items/item-2456.png',
  },
  {
    id: 2455,
    name: 'Crossbow',
    category: 'Armas (distância)',
    attack: 0,
    defense: 0,
    twoHanded: true,
    level: 0,
    vocations: ['Paladin'],
    imbuements: '1 slot(s) de imbuement',
    categoriesText: 'distância, poder de perfuração',
    price: 160,
    droppedBy: ['Minotaur Archer', 'Dwarf Soldier', 'Hunter'],
    spriteUrl: '/generated/cyclopedia/items/item-2455.png',
  },
  {
    id: 8851,
    name: 'Royal crossbow',
    category: 'Armas (distância)',
    attack: 5,
    defense: 0,
    twoHanded: true,
    level: 130,
    vocations: ['Paladin'],
    imbuements: '3 slot(s) de imbuement',
    categoriesText: 'crítico, dano elemental, life leech, mana leech',
    price: 35000,
    droppedBy: ['Grim Reaper', 'Juggernaut', 'Demon'],
    spriteUrl: '/generated/cyclopedia/items/item-8851.png',
  },
  {
    id: 8852,
    name: 'Warsinger bow',
    category: 'Armas (distância)',
    attack: 3,
    defense: 0,
    twoHanded: true,
    level: 80,
    vocations: ['Paladin'],
    imbuements: '3 slot(s) de imbuement',
    categoriesText: 'crítico, dano elemental, life leech, mana leech',
    price: 26000,
    droppedBy: ['Grand Master Oberon', 'Dark Torturer', 'Fury'],
    spriteUrl: '/generated/cyclopedia/items/item-8852.png',
  },
  {
    id: 2190,
    name: 'Wand of vortex',
    category: 'Wands & Rods',
    attack: 13,
    defense: 0,
    twoHanded: false,
    level: 7,
    vocations: ['Sorcerer'],
    imbuements: '1 slot(s) de imbuement',
    categoriesText: 'dano de energia',
    price: 100,
    droppedBy: ['Minotaur Mage', 'Orc Shaman'],
    spriteUrl: '/generated/cyclopedia/items/item-2190.png',
  },
  {
    id: 2182,
    name: 'Snakebite rod',
    category: 'Wands & Rods',
    attack: 13,
    defense: 0,
    twoHanded: false,
    level: 7,
    vocations: ['Druid'],
    imbuements: '1 slot(s) de imbuement',
    categoriesText: 'dano de terra',
    price: 100,
    droppedBy: ['Swamp Troll', 'Witch'],
    spriteUrl: '/generated/cyclopedia/items/item-2182.png',
  },
  {
    id: 2187,
    name: 'Wand of inferno',
    category: 'Wands & Rods',
    attack: 65,
    defense: 0,
    twoHanded: false,
    level: 33,
    vocations: ['Sorcerer'],
    imbuements: '2 slot(s) de imbuement',
    categoriesText: 'dano de fogo, mana leech',
    price: 3000,
    droppedBy: ['Dragon', 'Dragon Lord', 'Warlock'],
    spriteUrl: '/generated/cyclopedia/items/item-2187.png',
  },
  {
    id: 2183,
    name: 'Hailstorm rod',
    category: 'Wands & Rods',
    attack: 65,
    defense: 0,
    twoHanded: false,
    level: 33,
    vocations: ['Druid'],
    imbuements: '2 slot(s) de imbuement',
    categoriesText: 'dano de gelo, mana leech',
    price: 3000,
    droppedBy: ['Ice Golem', 'Frost Dragon', 'Warlock'],
    spriteUrl: '/generated/cyclopedia/items/item-2183.png',
  },
  {
    id: 2520,
    name: 'Demon shield',
    category: 'Escudos',
    attack: 0,
    defense: 35,
    twoHanded: false,
    level: 35,
    vocations: ['Todas'],
    imbuements: '1 slot(s) de imbuement',
    categoriesText: 'defesa elemental',
    price: 30000,
    droppedBy: ['Demon', 'Grand Master Oberon', 'Ferumbras'],
    spriteUrl: '/generated/cyclopedia/items/item-2520.png',
  },
  {
    id: 2514,
    name: 'Mastermind shield',
    category: 'Escudos',
    attack: 0,
    defense: 37,
    twoHanded: false,
    level: 50,
    vocations: ['Todas'],
    imbuements: '1 slot(s) de imbuement',
    categoriesText: 'defesa elemental, shielding',
    price: 50000,
    droppedBy: ['Demon', 'Juggernaut', 'Grim Reaper'],
    spriteUrl: '/generated/cyclopedia/items/item-2514.png',
  },
  {
    id: 2471,
    name: 'Golden helmet',
    category: 'Elmos',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 100,
    vocations: ['Todas'],
    imbuements: '2 slot(s) de imbuement',
    categoriesText: 'armadura 12, proteção física',
    price: 150000,
    droppedBy: ['Ferumbras', 'Morgaroth', 'Ghazbaran'],
    spriteUrl: '/generated/cyclopedia/items/item-2471.png',
  },
  {
    id: 2498,
    name: 'Royal helmet',
    category: 'Elmos',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 40,
    vocations: ['Todas'],
    imbuements: '2 slot(s) de imbuement',
    categoriesText: 'armadura 9, proteção física',
    price: 30000,
    droppedBy: ['Dragon Lord', 'Hero', 'Demon'],
    spriteUrl: '/generated/cyclopedia/items/item-2498.png',
  },
  {
    id: 2472,
    name: 'Magic plate armor',
    category: 'Armaduras',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 100,
    vocations: ['Knight', 'Paladin'],
    imbuements: '2 slot(s) de imbuement',
    categoriesText: 'armadura 17, life leech',
    price: 90000,
    droppedBy: ['Demon', 'Grand Master Oberon', 'Ferumbras', 'Orshabaal'],
    spriteUrl: '/generated/cyclopedia/items/item-2472.png',
  },
  {
    id: 2470,
    name: 'Golden armor',
    category: 'Armaduras',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 35,
    vocations: ['Knight', 'Paladin'],
    imbuements: '2 slot(s) de imbuement',
    categoriesText: 'armadura 14, life leech',
    price: 20000,
    droppedBy: ['Demon', 'Hero', 'Grand Master Oberon'],
    spriteUrl: '/generated/cyclopedia/items/item-2470.png',
  },
  {
    id: 2494,
    name: 'Demon armor',
    category: 'Armaduras',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 60,
    vocations: ['Knight', 'Paladin'],
    imbuements: '2 slot(s) de imbuement',
    categoriesText: 'armadura 16, life leech, proteção de fogo',
    price: 50000,
    droppedBy: ['Demon', 'Annihilator Quest', 'Grand Master Oberon'],
    spriteUrl: '/generated/cyclopedia/items/item-2494.png',
  },
  {
    id: 2477,
    name: 'Knight legs',
    category: 'Calças',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 20,
    vocations: ['Knight', 'Paladin'],
    imbuements: '1 slot(s) de imbuement',
    categoriesText: 'armadura 8',
    price: 5000,
    droppedBy: ['Giant Spider', 'Dragon', 'Hero'],
    spriteUrl: '/generated/cyclopedia/items/item-2477.png',
  },
  {
    id: 2478,
    name: 'Brass legs',
    category: 'Calças',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 0,
    vocations: ['Todas'],
    imbuements: 'sem slots',
    categoriesText: 'armadura 5',
    price: 49,
    droppedBy: ['Minotaur', 'Orc Warrior', 'Troll'],
    spriteUrl: '/generated/cyclopedia/items/item-2478.png',
  },
  {
    id: 2468,
    name: 'Plate legs',
    category: 'Calças',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 0,
    vocations: ['Todas'],
    imbuements: 'sem slots',
    categoriesText: 'armadura 7',
    price: 115,
    droppedBy: ['Cyclops', 'Minotaur Guard', 'Orc Berserker'],
    spriteUrl: '/generated/cyclopedia/items/item-2468.png',
  },
  {
    id: 2195,
    name: 'Boots of haste',
    category: 'Botas',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 0,
    vocations: ['Todas'],
    imbuements: '1 slot(s) de imbuement',
    categoriesText: 'velocidade +20',
    price: 30000,
    droppedBy: ['Necromancer', 'Black Knight', 'Banshee'],
    spriteUrl: '/generated/cyclopedia/items/item-2195.png',
  },
  {
    id: 2645,
    name: 'Steel boots',
    category: 'Botas',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 0,
    vocations: ['Todas'],
    imbuements: '1 slot(s) de imbuement',
    categoriesText: 'armadura 3, proteção física',
    price: 30000,
    droppedBy: ['Demon', 'Behemoth', 'Dragon Lord'],
    spriteUrl: '/generated/cyclopedia/items/item-2645.png',
  },
  {
    id: 2197,
    name: 'Stone skin amulet',
    category: 'Amuletos',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 0,
    vocations: ['Todas'],
    imbuements: 'sem slots',
    categoriesText: 'proteção física 80%, proteção de morte 80%',
    price: 500,
    droppedBy: ['Merlkin', 'Warlock', 'Hydra'],
    spriteUrl: '/generated/cyclopedia/items/item-2197.png',
  },
  {
    id: 2173,
    name: 'Amulet of loss',
    category: 'Amuletos',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 0,
    vocations: ['Todas'],
    imbuements: 'sem slots',
    categoriesText: 'proteção contra perda de itens na morte',
    price: 50000,
    droppedBy: ['Eremite', 'Grand Master Oberon'],
    spriteUrl: '/generated/cyclopedia/items/item-2173.png',
  },
  {
    id: 2167,
    name: 'Energy ring',
    category: 'Anéis',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 0,
    vocations: ['Todas'],
    imbuements: 'sem slots',
    categoriesText: 'converte dano para consumo de mana (Magic Shield)',
    price: 100,
    droppedBy: ['Tarantula', 'Dragon', 'Warlock', 'Demon'],
    spriteUrl: '/generated/cyclopedia/items/item-2167.png',
  },
  {
    id: 2168,
    name: 'Life ring',
    category: 'Anéis',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 0,
    vocations: ['Todas'],
    imbuements: 'sem slots',
    categoriesText: 'regeneração acelerada de vida e mana',
    price: 50,
    droppedBy: ['Ghoul', 'Vampire', 'Necromancer'],
    spriteUrl: '/generated/cyclopedia/items/item-2168.png',
  },
  {
    id: 2148,
    name: 'Gold coin',
    category: 'Trinkets',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 0,
    vocations: ['Todas'],
    imbuements: 'sem slots',
    categoriesText: 'moeda de ouro padrão',
    price: 1,
    droppedBy: ['Spider', 'Troll', 'Minotaur', 'Cyclops', 'Demon'],
    spriteUrl: '/generated/cyclopedia/items/item-2148.png',
  },
  {
    id: 2152,
    name: 'Platinum coin',
    category: 'Trinkets',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 0,
    vocations: ['Todas'],
    imbuements: 'sem slots',
    categoriesText: 'moeda valiosa equivalente a 100 gold coins',
    price: 100,
    droppedBy: ['Dragon', 'Dragon Lord', 'Grand Master Oberon', 'Hero'],
    spriteUrl: '/generated/cyclopedia/items/item-2152.png',
  },
  {
    id: 2160,
    name: 'Crystal coin',
    category: 'Trinkets',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 0,
    vocations: ['Todas'],
    imbuements: 'sem slots',
    categoriesText: 'moeda preciosa equivalente a 10.000 gold coins',
    price: 10000,
    droppedBy: ['Grand Master Oberon', 'Demon', 'Ferumbras', 'Juggernaut'],
    spriteUrl: '/generated/cyclopedia/items/item-2160.png',
  },
  {
    id: 5879,
    name: 'Spider silk',
    category: 'Trinkets',
    attack: 0,
    defense: 0,
    twoHanded: false,
    level: 0,
    vocations: ['Todas'],
    imbuements: 'sem slots',
    categoriesText: 'teia de aranha valiosa para imbuements e addons',
    price: 1000,
    droppedBy: ['Giant Spider', 'Spider', 'Tarantula'],
    spriteUrl: '/generated/cyclopedia/items/item-5879.png',
  },
];

const canonicalItemMap = new Map<number, ItemEntry>();
for (const it of INITIAL_CANONICAL_ITEMS) {
  canonicalItemMap.set(it.id, it);
}
if (rawCyclopediaCatalog && Array.isArray((rawCyclopediaCatalog as any).items)) {
  for (const it of ((rawCyclopediaCatalog as any).items as ItemEntry[])) {
    if (!canonicalItemMap.has(it.id)) {
      canonicalItemMap.set(it.id, it);
    }
  }
}
export const CANONICAL_CYCLOPEDIA_ITEMS: ItemEntry[] = Array.from(canonicalItemMap.values());

// Canonical Bestiary monsters matching Screenshot 2 & 3
const INITIAL_CANONICAL_MONSTERS: BestiaryMonster[] = [
  {
    id: 'spider',
    name: 'Spider',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 40,
    exp: 12,
    speed: 76,
    armor: 3,
    spriteUrl: '/generated/bestiary/spider.png',
    resistances: {
      physical: 0,
      energy: 0,
      earth: 10,
      fire: 40, // Fire weakness / resistance bar in green (Screenshot 3)
      ice: 0,
      holy: 0,
      death: 0,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 12, rare: false },
      { id: 5879, name: 'Spider silk', count: 1, rare: true },
    ],
    locations: ['Giant Spider', 'Thais Caves', 'Fibula', 'Plains of Havoc'],
  },
  {
    id: 'troll',
    name: 'Troll',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 50,
    exp: 20,
    speed: 170,
    armor: 10,
    spriteUrl: '/generated/bestiary/troll.png',
    resistances: {
      physical: 0,
      energy: -10,
      earth: 0,
      fire: -10,
      ice: 10,
      holy: 0,
      death: 0,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 8, rare: false },
      { id: 2461, name: 'Leather helmet', count: 1, rare: true },
    ],
    locations: ['Troll Caves', 'Thais East', 'Edron', 'Carlin'],
  },
  {
    id: 'swamp-troll',
    name: 'Swamp Troll',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 55,
    exp: 25,
    speed: 170,
    armor: 15,
    spriteUrl: '/generated/bestiary/swamp-troll.png',
    resistances: {
      physical: 0,
      energy: -10,
      earth: 40,
      fire: -20,
      ice: 0,
      holy: 0,
      death: 0,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 15, rare: false },
      { id: 2802, name: 'Medicine pouch', count: 1, rare: true },
    ],
    locations: ['Venore Swamps', 'Port Hope'],
  },
  {
    id: 'elf',
    name: 'Elf',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 100,
    exp: 42,
    speed: 170,
    armor: 10,
    spriteUrl: '/generated/bestiary/elf.png',
    resistances: {
      physical: 0,
      energy: 0,
      earth: 20,
      fire: -10,
      ice: 0,
      holy: 20,
      death: -10,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 25, rare: false },
      { id: 5921, name: 'Elven scouting glass', count: 1, rare: true },
    ],
    locations: ['Shadowthorn', 'Venore', 'Yalahar'],
  },
  {
    id: 'minotaur',
    name: 'Minotaur',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 100,
    exp: 50,
    speed: 170,
    armor: 15,
    spriteUrl: '/generated/bestiary/minotaur.png',
    resistances: {
      physical: 0,
      energy: 0,
      earth: 0,
      fire: 10,
      ice: -10,
      holy: 10,
      death: -10,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 20, rare: false },
      { id: 5878, name: 'Minotaur leather', count: 1, rare: true },
    ],
    locations: ['Mintwallin', 'Thais Mino Cave', 'Darashia'],
  },
  {
    id: 'amazon',
    name: 'Amazon',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 110,
    exp: 60,
    speed: 180,
    armor: 10,
    spriteUrl: '/generated/bestiary/amazon.png',
    resistances: {
      physical: 0,
      energy: 0,
      earth: 10,
      fire: 0,
      ice: -10,
      holy: 10,
      death: 0,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 20, rare: false },
      { id: 2467, name: 'Leather armor', count: 1, rare: false },
      { id: 2145, name: 'Small diamond', count: 1, rare: true },
    ],
    locations: ['Amazon Camp', 'Carlin', 'Venore'],
  },
  {
    id: 'minotaur-archer',
    name: 'Minotaur Archer',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 100,
    exp: 65,
    speed: 170,
    armor: 10,
    spriteUrl: '/generated/bestiary/minotaur-archer.png',
    resistances: {
      physical: 0,
      energy: 0,
      earth: 0,
      fire: 10,
      ice: -10,
      holy: 10,
      death: -10,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 30, rare: false },
      { id: 2456, name: 'Bow', count: 1, rare: true },
    ],
    locations: ['Mintwallin', 'Darashia', 'Thais'],
  },
  {
    id: 'elf-scout',
    name: 'Elf Scout',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 160,
    exp: 75,
    speed: 170,
    armor: 10,
    spriteUrl: '/generated/bestiary/elf-scout.png',
    resistances: {
      physical: 0,
      energy: 0,
      earth: 20,
      fire: -10,
      ice: 0,
      holy: 20,
      death: -10,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 35, rare: false },
      { id: 2456, name: 'Bow', count: 1, rare: true },
      { id: 5881, name: 'Elven hoof', count: 1, rare: true },
    ],
    locations: ['Shadowthorn', 'Yalahar', 'Drefia'],
  },
  {
    id: 'valkyrie',
    name: 'Valkyrie',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 190,
    exp: 85,
    speed: 190,
    armor: 20,
    spriteUrl: '/generated/bestiary/valkyrie.png',
    resistances: {
      physical: 0,
      energy: 0,
      earth: 10,
      fire: 0,
      ice: -10,
      holy: 10,
      death: 0,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 45, rare: false },
      { id: 2459, name: 'Iron helmet', count: 1, rare: true },
    ],
    locations: ['Amazon Camp', 'Carlin', 'Edron'],
  },
  {
    id: 'sibang',
    name: 'Sibang',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 225,
    exp: 105,
    speed: 200,
    armor: 15,
    spriteUrl: '/generated/bestiary/sibang.png',
    resistances: {
      physical: 0,
      energy: 0,
      earth: 20,
      fire: -10,
      ice: 0,
      holy: 0,
      death: 0,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 30, rare: false },
      { id: 5883, name: 'Ape fur', count: 1, rare: true },
    ],
    locations: ['Banuta', 'Port Hope'],
  },
  {
    id: 'kongra',
    name: 'Kongra',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 340,
    exp: 115,
    speed: 210,
    armor: 20,
    spriteUrl: '/generated/bestiary/kongra.png',
    resistances: {
      physical: 0,
      energy: 0,
      earth: 20,
      fire: -10,
      ice: 0,
      holy: 0,
      death: 0,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 40, rare: false },
      { id: 5883, name: 'Ape fur', count: 1, rare: true },
    ],
    locations: ['Banuta', 'Port Hope', 'Tiquanda'],
  },
  {
    id: 'tarantula',
    name: 'Tarantula',
    stars: 2,
    difficulty: 'Médio',
    killsNeeded: 500,
    hp: 225,
    exp: 120,
    speed: 210,
    armor: 10,
    spriteUrl: '/generated/bestiary/tarantula.png',
    resistances: {
      physical: 0,
      energy: 0,
      earth: 40,
      fire: -20,
      ice: 0,
      holy: 0,
      death: 0,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 40, rare: false },
      { id: 2167, name: 'Energy ring', count: 1, rare: true },
      { id: 5879, name: 'Spider silk', count: 1, rare: true },
    ],
    locations: ['Port Hope Caves', 'Tiquanda', 'Darashia'],
  },
  {
    id: 'merlkin',
    name: 'Merlkin',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 235,
    exp: 145,
    speed: 200,
    armor: 15,
    spriteUrl: '/generated/bestiary/merlkin.png',
    resistances: {
      physical: 0,
      energy: 0,
      earth: 20,
      fire: -10,
      ice: 0,
      holy: 0,
      death: 0,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 50, rare: false },
      { id: 5883, name: 'Ape fur', count: 1, rare: true },
      { id: 2197, name: 'Stone skin amulet', count: 1, rare: true },
    ],
    locations: ['Banuta', 'Port Hope'],
  },
  {
    id: 'cyclops',
    name: 'Cyclops',
    stars: 2,
    difficulty: 'Médio',
    killsNeeded: 500,
    hp: 260,
    exp: 150,
    speed: 200,
    armor: 20,
    spriteUrl: '/generated/bestiary/cyclops.png',
    resistances: {
      physical: 0,
      energy: 10,
      earth: -10,
      fire: 0,
      ice: 0,
      holy: 20,
      death: -20,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 55, rare: false },
      { id: 7398, name: 'Cyclops toe', count: 1, rare: true },
      { id: 2510, name: 'Plate shield', count: 1, rare: false },
    ],
    locations: ['Mount Sternum', 'Thais Cyclops Camp', 'Plains of Havoc'],
  },
  {
    id: 'minotaur-mage',
    name: 'Minotaur Mage',
    stars: 2,
    difficulty: 'Médio',
    killsNeeded: 500,
    hp: 155,
    exp: 150,
    speed: 170,
    armor: 15,
    spriteUrl: '/generated/bestiary/minotaur-mage.png',
    resistances: {
      physical: 0,
      energy: 20,
      earth: 0,
      fire: 30,
      ice: -10,
      holy: 10,
      death: -10,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 70, rare: false },
      { id: 2190, name: 'Wand of vortex', count: 1, rare: true },
      { id: 5878, name: 'Minotaur leather', count: 1, rare: true },
    ],
    locations: ['Mintwallin', 'Thais Mino Cave', 'Darashia'],
  },
  {
    id: 'rotworm',
    name: 'Rotworm',
    stars: 1,
    difficulty: 'Fácil',
    killsNeeded: 250,
    hp: 65,
    exp: 40,
    speed: 170,
    armor: 8,
    spriteUrl: '/generated/bestiary/rotworm.png',
    resistances: {
      physical: 0,
      energy: 0,
      earth: 20,
      fire: 0,
      ice: 0,
      holy: 10,
      death: -10,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 17, rare: false },
    ],
    locations: ['Thais Sewers', 'Venore Caves', 'Edron Caves'],
  },
  {
    id: 'dragon',
    name: 'Dragon',
    stars: 3,
    difficulty: 'Difícil',
    killsNeeded: 1000,
    hp: 1000,
    exp: 700,
    speed: 210,
    armor: 25,
    spriteUrl: '/generated/bestiary/dragon.png',
    resistances: {
      physical: 0,
      energy: -10,
      earth: 80,
      fire: 100,
      ice: -10,
      holy: 0,
      death: 0,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 110, rare: false },
      { id: 2187, name: 'Wand of inferno', count: 1, rare: true },
      { id: 2516, name: 'Dragon shield', count: 1, rare: true },
    ],
    locations: ['Dragon Lairs', 'Ankrahmun', 'Venore', 'Thais'],
  },
  {
    id: 'demon',
    name: 'Demon',
    stars: 4,
    difficulty: 'Extremo',
    killsNeeded: 2500,
    hp: 8200,
    exp: 6000,
    speed: 260,
    armor: 40,
    spriteUrl: '/generated/bestiary/demon.png',
    resistances: {
      physical: 30,
      energy: 30,
      earth: 40,
      fire: 100,
      ice: -15,
      holy: -15,
      death: 30,
    },
    drops: [
      { id: 2148, name: 'Gold coin', count: 200, rare: false },
      { id: 2160, name: 'Crystal coin', count: 1, rare: true },
      { id: 2520, name: 'Demon shield', count: 1, rare: true },
      { id: 2472, name: 'Magic plate armor', count: 1, rare: true },
    ],
    locations: ['Goroma', 'Hellgate', 'Edron Demon Hell', 'Yalahar Magician Quarter'],
  },
];

const canonicalMonsterMap = new Map<string, BestiaryMonster>();
for (const m of INITIAL_CANONICAL_MONSTERS) {
  canonicalMonsterMap.set(m.id.toLowerCase(), m);
}
if (rawCyclopediaCatalog && Array.isArray((rawCyclopediaCatalog as any).monsters)) {
  for (const m of ((rawCyclopediaCatalog as any).monsters as BestiaryMonster[])) {
    const k = m.id.toLowerCase();
    if (!canonicalMonsterMap.has(k)) {
      canonicalMonsterMap.set(k, m);
    }
  }
}
export const CANONICAL_BESTIARY_MONSTERS: BestiaryMonster[] = Array.from(canonicalMonsterMap.values());

export function getCyclopediaItems(): ItemEntry[] {
  return CANONICAL_CYCLOPEDIA_ITEMS;
}

export function getBestiaryMonsters(): BestiaryMonster[] {
  return CANONICAL_BESTIARY_MONSTERS;
}

// Canonical Bosstiary bosses matching Screenshot 4 & 5
export const CANONICAL_BOSSTIARY_BOSSES: BosstiaryBoss[] = [
  {
    id: 'grand-master-oberon',
    name: 'Grand Master Oberon',
    tier: 'Archfoe',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 270000,
    exp: 50000,
    summons: ['Falcon Knight', 'Falcon Paladin'],
    cooldown: '11h 44m',
    spriteUrl: '/generated/bestiary/grand-master-oberon.png',
    resistances: {
      physical: 30,
      energy: 20,
      earth: 20,
      fire: 20,
      ice: 20,
      holy: 40,
      death: 20,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
      { id: 2152, name: 'Platinum coin' },
      { id: 2520, name: 'Demon shield' },
      { id: 2160, name: 'Crystal coin' },
      { id: 2470, name: 'Golden armor' },
    ],
    dropsRare: [
      { id: 7414, name: 'Abyss hammer' },
      { id: 7436, name: 'Angelic axe' },
      { id: 2453, name: 'Arcane staff' },
      { id: 7404, name: 'Assassin dagger' },
      { id: 2494, name: 'Demon armor' },
      { id: 2472, name: 'Magic plate armor' },
    ],
  },
  {
    id: 'brokul',
    name: 'Brokul',
    tier: 'Archfoe',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 120000,
    exp: 35000,
    summons: ['Quara Predator', 'Quara Constrictor'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/brokul.png',
    resistances: {
      physical: 10,
      energy: -20,
      earth: 10,
      fire: 50,
      ice: 100,
      holy: 0,
      death: 10,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
      { id: 2152, name: 'Platinum coin' },
    ],
    dropsRare: [
      { id: 2520, name: 'Demon shield' },
      { id: 2470, name: 'Golden armor' },
    ],
  },
  {
    id: 'scarlett-etzel',
    name: 'Scarlett Etzel',
    tier: 'Bane',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 300000,
    exp: 60000,
    summons: ['Cobra Assassin', 'Cobra Scout'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/scarlett-etzel.png',
    resistances: {
      physical: 20,
      energy: 20,
      earth: 50,
      fire: 0,
      ice: 20,
      holy: 20,
      death: 20,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
      { id: 2152, name: 'Platinum coin' },
    ],
    dropsRare: [
      { id: 2400, name: 'Magic sword' },
      { id: 2472, name: 'Magic plate armor' },
    ],
  },
  {
    id: 'ratmiral-blackwhiskers',
    name: 'Ratmiral Blackwhiskers',
    tier: 'Archfoe',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 95000,
    exp: 28000,
    summons: ['Pirate Rat', 'Cave Rat'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/ratmiral-blackwhiskers.png',
    resistances: {
      physical: 15,
      energy: 0,
      earth: 10,
      fire: -10,
      ice: 10,
      holy: 0,
      death: 0,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
      { id: 2152, name: 'Platinum coin' },
    ],
    dropsRare: [
      { id: 2195, name: 'Boots of haste' },
    ],
  },
  {
    id: 'the-nightmare-beast',
    name: 'The Nightmare Beast',
    tier: 'Nemesis',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 450000,
    exp: 120000,
    summons: ['Nightmare Scion', 'Grim Reaper'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/the-nightmare-beast.png',
    resistances: {
      physical: 30,
      energy: 30,
      earth: 30,
      fire: 30,
      ice: 30,
      holy: -10,
      death: 50,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
      { id: 2152, name: 'Platinum coin' },
      { id: 2160, name: 'Crystal coin' },
    ],
    dropsRare: [
      { id: 7414, name: 'Abyss hammer' },
      { id: 2472, name: 'Magic plate armor' },
    ],
  },
  {
    id: 'shadowpelt',
    name: 'Shadowpelt',
    tier: 'Archfoe',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 160000,
    exp: 40000,
    summons: ['Dark Wolf'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/shadowpelt.png',
    resistances: {
      physical: 20,
      energy: 10,
      earth: 10,
      fire: -10,
      ice: 20,
      holy: -10,
      death: 40,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
      { id: 2152, name: 'Platinum coin' },
    ],
    dropsRare: [
      { id: 2470, name: 'Golden armor' },
    ],
  },
  {
    id: 'brain-head',
    name: 'Brain Head',
    tier: 'Archfoe',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 180000,
    exp: 42000,
    summons: ['Elder Bonelord'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/brain-head.png',
    resistances: {
      physical: 10,
      energy: 30,
      earth: 20,
      fire: -10,
      ice: 10,
      holy: 10,
      death: 30,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
      { id: 2152, name: 'Platinum coin' },
    ],
    dropsRare: [
      { id: 2453, name: 'Arcane staff' },
    ],
  },
  {
    id: 'the-time-guardian',
    name: 'The Time Guardian',
    tier: 'Archfoe',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 200000,
    exp: 45000,
    summons: ['Time Warden'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/the-time-guardian.png',
    resistances: {
      physical: 20,
      energy: 40,
      earth: 20,
      fire: 20,
      ice: 20,
      holy: 30,
      death: 30,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
      { id: 2152, name: 'Platinum coin' },
    ],
    dropsRare: [
      { id: 2160, name: 'Crystal coin' },
      { id: 2400, name: 'Magic sword' },
    ],
  },
  {
    id: 'black-vixen',
    name: 'Black Vixen',
    tier: 'Archfoe',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 150000,
    exp: 38000,
    summons: ['Werewolf'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/black-vixen.png',
    resistances: {
      physical: 25,
      energy: 10,
      earth: 10,
      fire: -10,
      ice: 20,
      holy: -10,
      death: 40,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
    ],
    dropsRare: [
      { id: 2470, name: 'Golden armor' },
    ],
  },
  {
    id: 'sharpclaw',
    name: 'Sharpclaw',
    tier: 'Archfoe',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 155000,
    exp: 39000,
    summons: ['Badger'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/sharpclaw.png',
    resistances: {
      physical: 20,
      energy: 10,
      earth: 20,
      fire: 10,
      ice: 10,
      holy: 0,
      death: 20,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
    ],
    dropsRare: [
      { id: 7404, name: 'Assassin dagger' },
    ],
  },
  {
    id: 'darkfang',
    name: 'Darkfang',
    tier: 'Archfoe',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 170000,
    exp: 41000,
    summons: ['Gloom Wolf'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/darkfang.png',
    resistances: {
      physical: 25,
      energy: 20,
      earth: 20,
      fire: 0,
      ice: 20,
      holy: -20,
      death: 50,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
      { id: 2152, name: 'Platinum coin' },
    ],
    dropsRare: [
      { id: 2477, name: 'Knight legs' },
    ],
  },
  {
    id: 'bloodback',
    name: 'Bloodback',
    tier: 'Archfoe',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 165000,
    exp: 40000,
    summons: ['Wereboar'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/bloodback.png',
    resistances: {
      physical: 25,
      energy: 10,
      earth: 20,
      fire: 10,
      ice: 10,
      holy: -10,
      death: 40,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
    ],
    dropsRare: [
      { id: 2498, name: 'Royal helmet' },
    ],
  },
  {
    id: 'ghulosh',
    name: 'Ghulosh',
    tier: 'Nemesis',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 500000,
    exp: 130000,
    summons: ['Ghulosh Spawn'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/ghulosh.png',
    resistances: {
      physical: 30,
      energy: 30,
      earth: 30,
      fire: 30,
      ice: 30,
      holy: 30,
      death: 50,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
      { id: 2152, name: 'Platinum coin' },
      { id: 2160, name: 'Crystal coin' },
    ],
    dropsRare: [
      { id: 2472, name: 'Magic plate armor' },
    ],
  },
  {
    id: 'lokathmor',
    name: 'Lokathmor',
    tier: 'Archfoe',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 420000,
    exp: 110000,
    summons: ['Demon'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/lokathmor.png',
    resistances: {
      physical: 30,
      energy: 20,
      earth: 20,
      fire: 50,
      ice: 0,
      holy: 20,
      death: 30,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
      { id: 2152, name: 'Platinum coin' },
    ],
    dropsRare: [
      { id: 2520, name: 'Demon shield' },
    ],
  },
  {
    id: 'mazzinor',
    name: 'Mazzinor',
    tier: 'Archfoe',
    stars: 1,
    prowess: 5,
    expertise: 20,
    mastery: 60,
    hp: 430000,
    exp: 115000,
    summons: ['Warlock'],
    cooldown: '20h',
    spriteUrl: '/generated/bestiary/mazzinor.png',
    resistances: {
      physical: 25,
      energy: 40,
      earth: 30,
      fire: 30,
      ice: 30,
      holy: 20,
      death: 40,
    },
    dropsCommon: [
      { id: 2148, name: 'Gold coin' },
      { id: 2152, name: 'Platinum coin' },
    ],
    dropsRare: [
      { id: 2453, name: 'Arcane staff' },
    ],
  },
];

// Boss Points rewards and perk unlock tree
export interface BossPointPerk {
  id: string;
  name: string;
  description: string;
  cost: number;
  unlocked: boolean;
  icon: string;
}

export const BOSS_POINT_PERKS: BossPointPerk[] = [
  {
    id: 'boss-loot-5',
    name: 'Bênção de Saques de Bosses (+5%)',
    description: 'Aumenta a probabilidade de obter itens raros de qualquer Boss em +5%.',
    cost: 50,
    unlocked: false,
    icon: '🎁',
  },
  {
    id: 'boss-cooldown-10',
    name: 'Foco Temporal (-10% Recarga)',
    description: 'Reduz o tempo de recarga para desafiar bosses em 10%.',
    cost: 100,
    unlocked: false,
    icon: '⏳',
  },
  {
    id: 'boss-exp-15',
    name: 'Maestria de Conquista (+15% XP de Boss)',
    description: 'Concede +15% de experiência permanente ao derrotar qualquer criatura Bosstiary.',
    cost: 150,
    unlocked: false,
    icon: '⭐',
  },
  {
    id: 'boss-damage-7',
    name: 'Vigor Lendário (+7% Dano em Bosses)',
    description: 'Seus ataques causam +7% de dano extra direto contra criaturas da categoria Bosstiary.',
    cost: 250,
    unlocked: false,
    icon: '⚔️',
  },
];

export function formatNumberWithDots(val: number): string {
  if (typeof val !== 'number' || isNaN(val)) return '0';
  return val.toLocaleString('pt-BR');
}

export function getDifficultyStars(stars: number, maxStars = 4): { filled: number; total: number } {
  const filled = Math.max(0, Math.min(maxStars, Math.round(stars)));
  return { filled, total: maxStars };
}
